import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AssignmentDetailsAfterSubmission(),
        ]),
      ),
    );
  }
}

class AssignmentDetailsAfterSubmission extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 65,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 66,
                top: 64,
                child: SizedBox(
                  width: 181,
                  height: 33,
                  child: Text(
                    'Assignment Details',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w500,
                      height: 0.90,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 121,
                child: Container(
                  width: 390,
                  height: 699,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF9FAFB),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: Colors.white),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          height: 916,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(side: BorderSide(color: Colors.white)),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 16,
                                top: 64,
                                child: Container(
                                  width: 358,
                                  height: 80,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFECFDF5),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 7,
                                                child: Container(
                                                  width: 31.75,
                                                  height: 34,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFF10B981),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 8,
                                                        top: 4.75,
                                                        child: Container(
                                                          width: 15.75,
                                                          height: 24,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 3.25,
                                                                child: Container(
                                                                  width: 15.75,
                                                                  height: 18,
                                                                  child: Row(
                                                                    mainAxisSize: MainAxisSize.min,
                                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                                    children: [
                                                                      Container(
                                                                        width: 15.75,
                                                                        height: 18,
                                                                        clipBehavior: Clip.antiAlias,
                                                                        decoration: ShapeDecoration(
                                                                          color: Colors.black.withValues(alpha: 0),
                                                                          shape: RoundedRectangleBorder(
                                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                          ),
                                                                        ),
                                                                        child: Stack(),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 43.75,
                                                top: 5,
                                                child: SizedBox(
                                                  width: 193,
                                                  height: 21,
                                                  child: Text(
                                                    'Assignment Submitted Successfully!',
                                                    style: TextStyle(
                                                      color: const Color(0xFF065F46),
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 168,
                                child: Container(
                                  width: 358,
                                  height: 216,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 3),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 20,
                                        top: 20,
                                        child: Container(
                                          width: 318,
                                          height: 56,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 314,
                                                  height: 24,
                                                  child: Text(
                                                    'Database Normalization Report',
                                                    style: TextStyle(
                                                      color: const Color(0xFF1F2937),
                                                      fontSize: 18,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 30,
                                                child: SizedBox(
                                                  width: 82,
                                                  height: 24,
                                                  child: Text(
                                                    '(DBMS)',
                                                    style: TextStyle(
                                                      color: const Color(0xFF1F2937),
                                                      fontSize: 18,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20,
                                        top: 92,
                                        child: Container(
                                          width: 318,
                                          height: 104,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 318,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 14,
                                                        child: Container(
                                                          width: 14,
                                                          height: 16,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 14,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 36,
                                                        top: 0,
                                                        child: Container(
                                                          width: 124.83,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 68,
                                                                  height: 19,
                                                                  child: Text(
                                                                    'Due Date',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Roboto Mono',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 21,
                                                                child: SizedBox(
                                                                  width: 125,
                                                                  height: 21,
                                                                  child: Text(
                                                                    '11 March 2025',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF374151),
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 60,
                                                child: Container(
                                                  width: 318,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 14,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 16,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 36,
                                                        top: 0,
                                                        child: Container(
                                                          width: 201.64,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 101,
                                                                  height: 19,
                                                                  child: Text(
                                                                    'Submitted on',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 21,
                                                                child: SizedBox(
                                                                  width: 202,
                                                                  height: 21,
                                                                  child: Text(
                                                                    '9 March 2025, 2:45 PM',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF374151),
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 408,
                                child: Container(
                                  width: 358,
                                  height: 164,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 3),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 20,
                                        top: 20,
                                        child: Container(
                                          width: 318,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: SizedBox(
                                                  width: 164,
                                                  height: 21,
                                                  child: Text(
                                                    'Submission Status',
                                                    style: TextStyle(
                                                      color: const Color(0xFF1F2937),
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20,
                                        top: 60,
                                        child: Container(
                                          width: 318,
                                          height: 84,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFFFFBEB),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(8),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 16,
                                                top: 16,
                                                child: Container(
                                                  width: 286,
                                                  height: 24,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 4,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 16,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 28,
                                                        top: 1,
                                                        child: SizedBox(
                                                          width: 135,
                                                          height: 21,
                                                          child: Text(
                                                            'Pending Review',
                                                            style: TextStyle(
                                                              color: const Color(0xFF92400E),
                                                              fontSize: 16,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 16,
                                                top: 48,
                                                child: Container(
                                                  width: 286,
                                                  height: 20,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 236,
                                                          height: 19,
                                                          child: Text(
                                                            'Expected Feedback: In 3 Days',
                                                            style: TextStyle(
                                                              color: const Color(0xFFB45309),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 596,
                                child: Container(
                                  width: 358,
                                  height: 128,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 3),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 20,
                                        top: 20,
                                        child: Container(
                                          width: 318,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: SizedBox(
                                                  width: 154,
                                                  height: 21,
                                                  child: Text(
                                                    'Progress Tracker',
                                                    style: TextStyle(
                                                      color: const Color(0xFF1F2937),
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20,
                                        top: 60,
                                        child: Container(
                                          width: 318,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 57.61,
                                                  height: 48,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 16.80,
                                                        top: 0,
                                                        child: Container(
                                                          width: 24,
                                                          height: 24,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF10B981),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 6.75,
                                                                top: 6,
                                                                child: Container(
                                                                  width: 10.50,
                                                                  height: 12,
                                                                  decoration: ShapeDecoration(
                                                                    color: Colors.black.withValues(alpha: 0),
                                                                    shape: RoundedRectangleBorder(
                                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                    ),
                                                                  ),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 0,
                                                                        child: Container(
                                                                          width: 10.50,
                                                                          height: 12,
                                                                          child: Row(
                                                                            mainAxisSize: MainAxisSize.min,
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                                            children: [
                                                                              Container(
                                                                                width: 10.50,
                                                                                height: 12,
                                                                                clipBehavior: Clip.antiAlias,
                                                                                decoration: ShapeDecoration(
                                                                                  color: Colors.black.withValues(alpha: 0),
                                                                                  shape: RoundedRectangleBorder(
                                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                                  ),
                                                                                ),
                                                                                child: Stack(),
                                                                              ),
                                                                            ],
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 58,
                                                          height: 16,
                                                          child: Text(
                                                            'Assigned',
                                                            style: TextStyle(
                                                              color: const Color(0xFF4B5563),
                                                              fontSize: 12,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 126.59,
                                                top: 0,
                                                child: Container(
                                                  width: 64.81,
                                                  height: 48,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 20.41,
                                                        top: 0,
                                                        child: Container(
                                                          width: 24,
                                                          height: 24,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF10B981),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 6.75,
                                                                top: 6,
                                                                child: Container(
                                                                  width: 10.50,
                                                                  height: 12,
                                                                  decoration: ShapeDecoration(
                                                                    color: Colors.black.withValues(alpha: 0),
                                                                    shape: RoundedRectangleBorder(
                                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                    ),
                                                                  ),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 0,
                                                                        child: Container(
                                                                          width: 10.50,
                                                                          height: 12,
                                                                          child: Row(
                                                                            mainAxisSize: MainAxisSize.min,
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                                            children: [
                                                                              Container(
                                                                                width: 10.50,
                                                                                height: 12,
                                                                                clipBehavior: Clip.antiAlias,
                                                                                decoration: ShapeDecoration(
                                                                                  color: Colors.black.withValues(alpha: 0),
                                                                                  shape: RoundedRectangleBorder(
                                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                                  ),
                                                                                ),
                                                                                child: Stack(),
                                                                              ),
                                                                            ],
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 65,
                                                          height: 16,
                                                          child: Text(
                                                            'Submitted',
                                                            style: TextStyle(
                                                              color: const Color(0xFF4B5563),
                                                              fontSize: 12,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 260.39,
                                                top: 0,
                                                child: Container(
                                                  width: 57.61,
                                                  height: 48,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 16.80,
                                                        top: 0,
                                                        child: Container(
                                                          width: 24,
                                                          height: 24,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFFE5E7EB),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 6.75,
                                                                top: 6,
                                                                child: Container(
                                                                  width: 10.50,
                                                                  height: 12,
                                                                  decoration: ShapeDecoration(
                                                                    color: Colors.black.withValues(alpha: 0),
                                                                    shape: RoundedRectangleBorder(
                                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                    ),
                                                                  ),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 0,
                                                                        child: Container(
                                                                          width: 10.50,
                                                                          height: 12,
                                                                          child: Row(
                                                                            mainAxisSize: MainAxisSize.min,
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                                            children: [
                                                                              Container(
                                                                                width: 10.50,
                                                                                height: 12,
                                                                                clipBehavior: Clip.antiAlias,
                                                                                decoration: ShapeDecoration(
                                                                                  color: Colors.black.withValues(alpha: 0),
                                                                                  shape: RoundedRectangleBorder(
                                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                                  ),
                                                                                ),
                                                                                child: Stack(),
                                                                              ),
                                                                            ],
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 58,
                                                          height: 16,
                                                          child: Text(
                                                            'Reviewed',
                                                            style: TextStyle(
                                                              color: const Color(0xFF9CA3AF),
                                                              fontSize: 12,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 22,
                                                top: 23,
                                                child: Container(
                                                  width: 274,
                                                  height: 2,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFE5E7EB),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 137,
                                                          height: 2,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF10B981),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 748,
                                child: Container(
                                  width: 358,
                                  height: 168,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 358,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF2563EB),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 119.98,
                                                top: 13,
                                                child: SizedBox(
                                                  width: 145,
                                                  height: 21,
                                                  child: Text(
                                                    'View Submission',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.white,
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto Mono',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 93.98,
                                                top: 13,
                                                child: Container(
                                                  width: 18,
                                                  height: 21,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 3,
                                                        child: Container(
                                                          width: 18,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 18,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 60,
                                        child: Container(
                                          width: 358,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF3F4F6),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 118.98,
                                                top: 13,
                                                child: SizedBox(
                                                  width: 145,
                                                  height: 21,
                                                  child: Text(
                                                    'Edit Submission',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF374151),
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto Mono',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 94.98,
                                                top: 13,
                                                child: Container(
                                                  width: 16,
                                                  height: 21,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 3,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 16,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 120,
                                        child: Container(
                                          width: 358,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 98.78,
                                                top: 13,
                                                child: SizedBox(
                                                  width: 183,
                                                  height: 21,
                                                  child: Text(
                                                    'Back to Assignments',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto Mono',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 76.78,
                                                top: 16,
                                                child: Container(
                                                  width: 14,
                                                  height: 16,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 14,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}