import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AssignmentDetails(),
        ]),
      ),
    );
  }
}

class AssignmentDetails extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 65,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 66,
                top: 64,
                child: SizedBox(
                  width: 181,
                  height: 33,
                  child: Text(
                    'Assignment Details',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w500,
                      height: 0.90,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 133,
                child: Container(
                  width: 390,
                  height: 196,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 358,
                          height: 28,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2,
                                child: SizedBox(
                                  width: 356,
                                  height: 24,
                                  child: Text(
                                    'Database Normalization Report (DBMS)',
                                    style: TextStyle(
                                      color: const Color(0xFF1F2937),
                                      fontSize: 20,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 60,
                        child: Container(
                          width: 358,
                          height: 120,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 24,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 4,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 24,
                                        top: 2,
                                        child: SizedBox(
                                          width: 146,
                                          height: 19,
                                          child: Text(
                                            'Due: March 11, 2025',
                                            style: TextStyle(
                                              color: const Color(0xFF374151),
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 36,
                                child: Container(
                                  width: 358,
                                  height: 24,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 4,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 24,
                                        top: 2,
                                        child: SizedBox(
                                          width: 90,
                                          height: 19,
                                          child: Text(
                                            'High Priority',
                                            style: TextStyle(
                                              color: const Color(0xFFEF4444),
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w500,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 72,
                                child: Container(
                                  width: 358,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 4,
                                        child: Container(
                                          width: 12,
                                          height: 16,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 12,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17.14,
                                        top: 6,
                                        child: SizedBox(
                                          width: 298,
                                          height: 19,
                                          child: Text(
                                            'Write a detailed report on the principles of database normalization.',
                                            style: TextStyle(
                                              color: const Color(0xFF374151),
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 345,
                child: Container(
                  width: 390,
                  height: 172,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 358,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2,
                                child: SizedBox(
                                  width: 100,
                                  height: 16,
                                  child: Text(
                                    'ATTACHMENTS',
                                    style: TextStyle(
                                      color: const Color(0xFF6B7280),
                                      fontSize: 14,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 48,
                        child: Container(
                          width: 358,
                          height: 108,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFE4F1FF),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 12,
                                        top: 12,
                                        child: Container(
                                          width: 148.95,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 4,
                                                child: Container(
                                                  width: 16,
                                                  height: 16,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 16,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 28,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 121,
                                                  height: 19,
                                                  child: Text(
                                                    'DBMS_Guide.pdf',
                                                    style: TextStyle(
                                                      color: const Color(0xFF374151),
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 330,
                                        top: 16,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 16,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 60,
                                child: Container(
                                  width: 358,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFDFEFFE),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 12,
                                        top: 12,
                                        child: Container(
                                          width: 138.53,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 4,
                                                child: Container(
                                                  width: 20,
                                                  height: 16,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 20,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 32,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 106,
                                                  height: 19,
                                                  child: Text(
                                                    'Reference Link',
                                                    style: TextStyle(
                                                      color: const Color(0xFF3B82F6),
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 330,
                                        top: 16,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 16,
                                                  height: 16,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 16,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 533,
                child: Container(
                  width: 390,
                  height: 292,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 358,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2,
                                child: SizedBox(
                                  width: 123,
                                  height: 16,
                                  child: Text(
                                    'YOUR SUBMISSION',
                                    style: TextStyle(
                                      color: const Color(0xFF6B7280),
                                      fontSize: 14,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 48,
                        child: Container(
                          width: 358,
                          height: 102,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFEDEDED),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 162.12,
                                top: 22.25,
                                child: Container(
                                  width: 33.75,
                                  height: 35,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 1.75,
                                        child: Container(
                                          width: 33.75,
                                          height: 30,
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 33.75,
                                                height: 30,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 54,
                                child: Container(
                                  width: 326,
                                  height: 24,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 96.66,
                                        top: 2,
                                        child: SizedBox(
                                          width: 133,
                                          height: 19,
                                          child: Text(
                                            'No submission yet',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF6B7280),
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 166,
                        child: Container(
                          width: 358,
                          height: 110,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 97,
                                top: 0,
                                child: Container(
                                  width: 164,
                                  height: 50,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        color: const Color(0xFFE5E7EB),
                                      ),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 29,
                                        top: 17,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 56,
                                        top: 17,
                                        child: SizedBox(
                                          width: 88,
                                          height: 19,
                                          child: Text(
                                            'Upload Files',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 97,
                                top: 62,
                                child: Container(
                                  width: 164,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, 0.50),
                                      end: Alignment(1.00, 0.50),
                                      colors: [const Color(0xFF8B5CF6), const Color(0xFFEC4899)],
                                    ),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 108.61,
                                        top: 12,
                                        child: Container(
                                          width: 140.78,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 12,
                                        child: SizedBox(
                                          width: 140,
                                          height: 19,
                                          child: Text(
                                            'Submit Assignment',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 16,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 841,
                child: Container(
                  width: 390,
                  height: 220,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 358,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2,
                                child: SizedBox(
                                  width: 196,
                                  height: 16,
                                  child: Text(
                                    'COMMENTS & DISCUSSION (2)',
                                    style: TextStyle(
                                      color: const Color(0xFF6B7280),
                                      fontSize: 14,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 48,
                        child: Container(
                          width: 358,
                          height: 96,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 40,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 32,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://placehold.co/32x32"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(9999),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 44,
                                        top: 0,
                                        child: Container(
                                          width: 183.34,
                                          height: 40,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 29,
                                                  height: 16,
                                                  child: Text(
                                                    'Alok',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 14,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w500,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 22,
                                                child: SizedBox(
                                                  width: 183,
                                                  height: 16,
                                                  child: Text(
                                                    'Do we need to include BCNF?',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 14,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 56,
                                child: Container(
                                  width: 358,
                                  height: 40,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 32,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://placehold.co/32x32"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(9999),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 44,
                                        top: 0,
                                        child: Container(
                                          width: 138.47,
                                          height: 40,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 83,
                                                  height: 16,
                                                  child: Text(
                                                    'Prof. Sharma',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 14,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w500,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 22,
                                                child: SizedBox(
                                                  width: 137,
                                                  height: 16,
                                                  child: Text(
                                                    'Yes, BCNF is required.',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 14,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 160,
                        child: Container(
                          width: 358,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF9FAFB),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 14,
                                child: Container(
                                  width: 16,
                                  height: 16,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 36,
                                top: 12,
                                child: Container(
                                  width: 286,
                                  height: 20,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: SizedBox(
                                          width: 111,
                                          height: 20,
                                          child: Text(
                                            'Add a comment...',
                                            style: TextStyle(
                                              color: const Color(0xFFADAEBC),
                                              fontSize: 14,
                                              fontFamily: 'Roboto',
                                              fontWeight: FontWeight.w400,
                                              height: 1.43,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 330,
                                top: 14,
                                child: Container(
                                  width: 16,
                                  height: 16,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 16,
                                          height: 16,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 16,
                                                height: 16,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: ShapeDecoration(
                                                  color: Colors.black.withValues(alpha: 0),
                                                  shape: RoundedRectangleBorder(
                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                  ),
                                                ),
                                                child: Stack(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}