import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          CreateClass(),
        ]),
      ),
    );
  }
}

class CreateClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 65,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 18,
                top: 118,
                child: Container(
                  width: 358,
                  height: 362,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C000000),
                        blurRadius: 2,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 326,
                          height: 330,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 326,
                                  height: 78,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 326,
                                          height: 20,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: SizedBox(
                                                  width: 116,
                                                  height: 18,
                                                  child: Text(
                                                    'Classroom Name',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 14,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 28,
                                        child: Container(
                                          width: 326,
                                          height: 50,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF9FAFB),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: const Color(0xFFE5E7EB),
                                              ),
                                              borderRadius: BorderRadius.circular(8),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 13,
                                                top: 17,
                                                child: Container(
                                                  width: 20,
                                                  height: 16,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 20,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 20,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 41,
                                                top: 13,
                                                child: Container(
                                                  width: 272,
                                                  height: 24,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 173,
                                                          height: 24,
                                                          child: Text(
                                                            'Enter classroom name',
                                                            style: TextStyle(
                                                              color: const Color(0xFFADAEBC),
                                                              fontSize: 16,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1.50,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9,
                                                top: 13,
                                                child: Container(
                                                  width: 24,
                                                  height: 24,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 94,
                                child: Container(
                                  width: 326,
                                  height: 78,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 326,
                                          height: 20,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: SizedBox(
                                                  width: 51,
                                                  height: 18,
                                                  child: Text(
                                                    'Subject',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 14,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 28,
                                        child: Container(
                                          width: 326,
                                          height: 50,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF9FAFB),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: const Color(0xFFE5E7EB),
                                              ),
                                              borderRadius: BorderRadius.circular(8),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 13,
                                                top: 17,
                                                child: Container(
                                                  width: 14,
                                                  height: 16,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 14,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 14,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 35,
                                                top: 13,
                                                child: Container(
                                                  width: 278,
                                                  height: 24,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 102,
                                                          height: 24,
                                                          child: Text(
                                                            'Enter subject',
                                                            style: TextStyle(
                                                              color: const Color(0xFFADAEBC),
                                                              fontSize: 16,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1.50,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 188,
                                child: Container(
                                  width: 326,
                                  height: 78,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 326,
                                          height: 20,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: SizedBox(
                                                  width: 91,
                                                  height: 18,
                                                  child: Text(
                                                    'Class Code',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B5563),
                                                      fontSize: 14,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 28,
                                        child: Container(
                                          width: 326,
                                          height: 50,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF9FAFB),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: const Color(0xFFE5E7EB),
                                              ),
                                              borderRadius: BorderRadius.circular(8),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 13,
                                                top: 17,
                                                child: Container(
                                                  width: 20,
                                                  height: 16,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 20,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 20,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 41,
                                                top: 13,
                                                child: Container(
                                                  width: 256,
                                                  height: 24,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 79,
                                                          height: 24,
                                                          child: Text(
                                                            'ABC123',
                                                            style: TextStyle(
                                                              color: const Color(0xFF6B7280),
                                                              fontSize: 16,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                              height: 1.50,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 297,
                                                top: 17,
                                                child: Container(
                                                  width: 16,
                                                  height: 16,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16,
                                                          height: 16,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 16,
                                                                height: 16,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 282,
                                child: Container(
                                  width: 326,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF3F4F6),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 49.06,
                                        top: 16,
                                        child: Container(
                                          width: 20,
                                          height: 16,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 20,
                                                  height: 16,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 20,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 77.06,
                                        top: 12,
                                        child: Container(
                                          width: 199.88,
                                          height: 24,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 196,
                                                  height: 20,
                                                  child: Text(
                                                    'Invite Students via Email',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF374151),
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 501,
                child: Container(
                  width: 164,
                  height: 48,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, 0.50),
                      end: Alignment(1.00, 0.50),
                      colors: [const Color(0xFF8B5CF6), const Color(0xFFEC4899)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 13,
                        top: 14,
                        child: SizedBox(
                          width: 138,
                          height: 20,
                          child: Text(
                            'Create Classroom',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 582,
                child: Container(
                  width: 358,
                  height: 208,
                  decoration: ShapeDecoration(
                    color: Colors.black.withValues(alpha: 0),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 2,
                        child: SizedBox(
                          width: 174,
                          height: 23,
                          child: Text(
                            'Existing Classrooms',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 1,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 358,
                          height: 164,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 82.94,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 47,
                                                  height: 20,
                                                  child: Text(
                                                    'DBMS',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 25,
                                                child: SizedBox(
                                                  width: 82,
                                                  height: 18,
                                                  child: Text(
                                                    '40 Students',
                                                    style: TextStyle(
                                                      color: const Color(0xFF6B7280),
                                                      fontSize: 14,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 332,
                                        top: 30,
                                        child: Container(
                                          width: 10,
                                          height: 16,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 10,
                                                  height: 16,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 10,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 88,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 80.98,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 2,
                                                child: SizedBox(
                                                  width: 64,
                                                  height: 20,
                                                  child: Text(
                                                    'AI & ML',
                                                    style: TextStyle(
                                                      color: Colors.black,
                                                      fontSize: 16,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 25,
                                                child: SizedBox(
                                                  width: 80,
                                                  height: 18,
                                                  child: Text(
                                                    '25 Students',
                                                    style: TextStyle(
                                                      color: const Color(0xFF6B7280),
                                                      fontSize: 14,
                                                      fontFamily: 'Lexend',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 332,
                                        top: 30,
                                        child: Container(
                                          width: 10,
                                          height: 16,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 10,
                                                  height: 16,
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    children: [
                                                      Container(
                                                        width: 10,
                                                        height: 16,
                                                        clipBehavior: Clip.antiAlias,
                                                        decoration: ShapeDecoration(
                                                          color: Colors.black.withValues(alpha: 0),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                          ),
                                                        ),
                                                        child: Stack(),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 60,
                top: 65,
                child: Text(
                  'Create Classroom',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}