import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MyClassrooms(),
        ]),
      ),
    );
  }
}

class MyClassrooms extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.04, 0.00),
              end: Alignment(1.03, 1.00),
              colors: [const Color(0xFFF1FFF6), const Color(0xFF13514D)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 65,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 60,
                top: 65,
                child: Text(
                  'DBMS - TE A',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 122,
                child: Container(
                  width: 390,
                  height: 460,
                  decoration: ShapeDecoration(
                    color: Colors.black.withValues(alpha: 0),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 358,
                          height: 428,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 125.67,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 18,
                                                        child: Container(
                                                          width: 8,
                                                          height: 8,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF10B981),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 20,
                                                        top: 0,
                                                        child: Container(
                                                          width: 105.67,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: SizedBox(
                                                                  width: 131,
                                                                  height: 20,
                                                                  child: Text(
                                                                    'Aditya Kumbhar',
                                                                    style: TextStyle(
                                                                      color: Colors.black,
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w500,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 25,
                                                                child: SizedBox(
                                                                  width: 53,
                                                                  height: 17,
                                                                  child: Text(
                                                                    'RS2025',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 252.69,
                                                top: 8,
                                                child: Container(
                                                  width: 73.31,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFD1FAE5),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 50,
                                                          height: 17,
                                                          child: Text(
                                                            'Graded',
                                                            style: TextStyle(
                                                              color: const Color(0xFF047857),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 88,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 111.30,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 18,
                                                        child: Container(
                                                          width: 8,
                                                          height: 8,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFFF97316),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 20,
                                                        top: 0,
                                                        child: Container(
                                                          width: 91.30,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: SizedBox(
                                                                  width: 120,
                                                                  height: 20,
                                                                  child: Text(
                                                                    'Aaryan Nagrale',
                                                                    style: TextStyle(
                                                                      color: Colors.black,
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w500,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 25,
                                                                child: SizedBox(
                                                                  width: 53,
                                                                  height: 17,
                                                                  child: Text(
                                                                    'RS2026',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 247.17,
                                                top: 8,
                                                child: Container(
                                                  width: 78.83,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFFEDD5),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 54,
                                                          height: 17,
                                                          child: Text(
                                                            'Pending',
                                                            style: TextStyle(
                                                              color: const Color(0xFFC2410C),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 176,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 115.95,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 18,
                                                        child: Container(
                                                          width: 8,
                                                          height: 8,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFFEF4444),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 20,
                                                        top: 0,
                                                        child: Container(
                                                          width: 95.95,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: SizedBox(
                                                                  width: 121,
                                                                  height: 20,
                                                                  child: Text(
                                                                    'Alok Bhorunde',
                                                                    style: TextStyle(
                                                                      color: Colors.black,
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w500,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 25,
                                                                child: SizedBox(
                                                                  width: 52,
                                                                  height: 17,
                                                                  child: Text(
                                                                    'RS2027',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 206.14,
                                                top: 8,
                                                child: Container(
                                                  width: 119.86,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFEE2E2),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 97,
                                                          height: 17,
                                                          child: Text(
                                                            'Not Submitted',
                                                            style: TextStyle(
                                                              color: const Color(0xFFB91C1C),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 264,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 131.45,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 18,
                                                        child: Container(
                                                          width: 8,
                                                          height: 8,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF10B981),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 20,
                                                        top: 0,
                                                        child: Container(
                                                          width: 111.45,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: SizedBox(
                                                                  width: 111,
                                                                  height: 20,
                                                                  child: Text(
                                                                    'Ananya Verma',
                                                                    style: TextStyle(
                                                                      color: Colors.black,
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w500,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 25,
                                                                child: SizedBox(
                                                                  width: 53,
                                                                  height: 17,
                                                                  child: Text(
                                                                    'RS2028',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 252.69,
                                                top: 8,
                                                child: Container(
                                                  width: 73.31,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFD1FAE5),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 50,
                                                          height: 17,
                                                          child: Text(
                                                            'Graded',
                                                            style: TextStyle(
                                                              color: const Color(0xFF047857),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 352,
                                child: Container(
                                  width: 358,
                                  height: 76,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x0C000000),
                                        blurRadius: 2,
                                        offset: Offset(0, 1),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 16,
                                        top: 16,
                                        child: Container(
                                          width: 326,
                                          height: 44,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 109.67,
                                                  height: 44,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 18,
                                                        child: Container(
                                                          width: 8,
                                                          height: 8,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFFF97316),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                              borderRadius: BorderRadius.circular(9999),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 20,
                                                        top: 0,
                                                        child: Container(
                                                          width: 89.67,
                                                          height: 44,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: SizedBox(
                                                                  width: 89,
                                                                  height: 20,
                                                                  child: Text(
                                                                    'Aman Joshi',
                                                                    style: TextStyle(
                                                                      color: Colors.black,
                                                                      fontSize: 16,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w500,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 25,
                                                                child: SizedBox(
                                                                  width: 53,
                                                                  height: 17,
                                                                  child: Text(
                                                                    'RS2029',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF6B7280),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 247.17,
                                                top: 8,
                                                child: Container(
                                                  width: 78.83,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFFEDD5),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 54,
                                                          height: 17,
                                                          child: Text(
                                                            'Pending',
                                                            style: TextStyle(
                                                              color: const Color(0xFFC2410C),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 751,
                child: Container(
                  width: 390,
                  height: 101,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFEFAEF),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE5E7EB),
                      ),
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(15),
                        topRight: Radius.circular(15),
                      ),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 17,
                        child: Container(
                          width: 358,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 358,
                                  height: 28,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 5,
                                        child: SizedBox(
                                          width: 53,
                                          height: 17,
                                          child: Text(
                                            'Sort By:',
                                            style: TextStyle(
                                              color: const Color(0xFF4B5563),
                                              fontSize: 14,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 149.28,
                                        top: 0,
                                        child: Container(
                                          width: 208.72,
                                          height: 28,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 63.20,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFF3F4F6),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 39,
                                                          height: 17,
                                                          child: Text(
                                                            'Name',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.black,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 71.20,
                                                top: 0,
                                                child: Container(
                                                  width: 66.56,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFF3F4F6),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 43,
                                                          height: 17,
                                                          child: Text(
                                                            'Status',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.black,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 145.77,
                                                top: 0,
                                                child: Container(
                                                  width: 62.95,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFF3F4F6),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 39,
                                                          height: 17,
                                                          child: Text(
                                                            'Score',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.black,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 40,
                                child: Container(
                                  width: 358,
                                  height: 28,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 5,
                                        child: SizedBox(
                                          width: 38,
                                          height: 17,
                                          child: Text(
                                            'Filter:',
                                            style: TextStyle(
                                              color: const Color(0xFF4B5563),
                                              fontSize: 14,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 129.88,
                                        top: 0,
                                        child: Container(
                                          width: 228.12,
                                          height: 28,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 40.98,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    gradient: LinearGradient(
                                                      begin: Alignment(-0.00, 0.47),
                                                      end: Alignment(1.00, 0.53),
                                                      colors: [const Color(0xFF8B5CF6), const Color(0xFFEC4899)],
                                                    ),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 17,
                                                          height: 17,
                                                          child: Text(
                                                            'All',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.white,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 48.98,
                                                top: 0,
                                                child: Container(
                                                  width: 78.83,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFF3F4F6),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 54,
                                                          height: 17,
                                                          child: Text(
                                                            'Pending',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.black,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 135.81,
                                                top: 0,
                                                child: Container(
                                                  width: 92.31,
                                                  height: 28,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFF3F4F6),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                      borderRadius: BorderRadius.circular(9999),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 12,
                                                        top: 5,
                                                        child: SizedBox(
                                                          width: 69,
                                                          height: 17,
                                                          child: Text(
                                                            'Submitted',
                                                            textAlign: TextAlign.center,
                                                            style: TextStyle(
                                                              color: Colors.black,
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w400,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}